name: Deploy Docker Container on EC2

on:
  push:
    branches:
      - feature/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # EC2 호스트 키 추가 (보안 강화)
      - name: Add EC2 Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # SSH 접속 확인 (환경 변수를 통한 안전한 비밀키 처리)
      - name: SSH 접속 확인
        run: |
          chmod 400 /dev/stdin
          ssh -i /dev/stdin ubuntu@${{ secrets.EC2_HOST }} <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      # 배포 스크립트 복사 및 실행
      - name: Copy and Run deploy.sh on EC2
        run: |
          scp -i /dev/stdin LongTermTravelPlanner/scripts/deploy.sh ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy.sh <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh -i /dev/stdin ubuntu@${{ secrets.EC2_HOST }} "chmod +x /home/ubuntu/deploy.sh && /home/ubuntu/deploy.sh" <<< "${{ secrets.SSH_PRIVATE_KEY }}"
