name: Deploy Docker Container on EC2

on:
  push:
    branches:
      - feature/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # SSH 접속 확인 단계
      - name: SSH 접속 확인
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }}

      # 배포 스크립트 복사 및 실행
      - name: Copy and Run deploy.sh on EC2
        run: |
          # 스크립트 복사 로그
          echo "Copying deploy.sh to EC2 instance..."
          scp -i private_key.pem -o StrictHostKeyChecking=no LongTermTravelPlanner/scripts/deploy.sh ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy.sh
          
          # 스크립트 복사 성공 여부 확인
          echo "Setting permissions and running deploy.sh on EC2..."
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "ls -l /home/ubuntu/deploy.sh && chmod +x /home/ubuntu/deploy.sh && /home/ubuntu/deploy.sh"

      # 보안: 비밀키 삭제
      - name: Remove private_key.pem for security
        run: |
          rm -f private_key.pem
