name: Deploy Docker Container on EC2

on:
  push:
    branches:
      - feature/cicd  # feature/cicd 브랜치에서만 트리거
    paths:
      - 'bami-AI/.github/workflows/deploy-on-ec2.yml'  # 이 파일이 변경될 때만 실행
      - 'LongTermTravelPlanner/scripts/deploy.sh'  # 이 파일이 변경될 때도 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}  # GitHub Secrets에 저장된 EC2 인스턴스의 퍼블릭 IP
          username: ubuntu  # EC2 인스턴스의 기본 사용자
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secrets에 저장된 프라이빗 키
          port: 22
          debug: true  # 디버그 모드 활성화
          script: |
            # 스크립트 동기화
            scp scripts/deploy.sh ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy.sh
            # ECR URI 환경 변수 설정
            export ECR_URI=${{ secrets.ECR_URI }}
            # 스크립트 실행 권한 부여 및 실행
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy.sh
