name: Deploy Docker Container on EC2

on:
  push:
    branches:
      - feature/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: SSH 접속 확인
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo 'SSH 접속 성공'; exit"

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true  # 디버그 모드 활성화
          script: |
            scp scripts/deploy.sh ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy.sh
            export ECR_URI=${{ secrets.ECR_URI }}
            chmod +x /home/ubuntu/deploy.sh
            /home/ubuntu/deploy
