name: Build and Push Docker image to ECR

on:
  push:
    branches:
      - main  # main 브랜치에 push되면 트리거
      - feature/docker  # 특정 브랜치에서 트리거

jobs:
  build_and_push_ecr:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 리포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Docker Buildx 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. AWS CLI 설치
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      # 4. AWS ECR 로그인 (AWS ECR과 Docker 레지스트리에 로그인)
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 528938155874.dkr.ecr.ap-northeast-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t bami-long ./LongTermTravelPlanner
          docker tag bami-long:latest 528938155874.dkr.ecr.ap-northeast-2.amazonaws.com/bami-ai:bami-long
      # 6. Docker 이미지 푸시 (ECR로 푸시)
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 528938155874.dkr.ecr.ap-northeast-2.amazonaws.com/bami-ai:bami-long
