name: Docker Build, Test, and Deploy to ECR

on:
  push:
    branches:
      - main
      - feature/cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # 도커 빌드 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # AWS ECR에 로그인 (IAM 권한 필요)
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_PUBLIC_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_KEY }}
          aws-region: ap-northeast-2

      # 도커 이미지 빌드
      - name: Build Docker image
        run: |
          cd LongTermTravelPlanner
          docker build -t bami-ai:latest -f Dockerfile.prod .

      # 빌드된 이미지를 기반으로 컨테이너 실행 및 테스트
      - name: Run and Test Docker Container
        run: |
          docker run -d --name test-container -p 8000:8000 bami-ai:latest
          sleep 10
          docker ps -a
          curl --fail http://localhost:8000 || exit 1

      # 테스트 성공 후 도커 이미지 태그 설정 (ECR 저장소 이름을 사용)
      - name: Tag Docker image
        run: |
          docker tag bami-ai:latest ${{ secrets.ECR_URI }}:latest

      # ECR에 이미지 푸시
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_URI }}:latest
