on:
  push:
    branches:
      - main
      - data/*
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r LongTermTravelPlanner/requirements.txt
          pip install boto3

      - name: Preprocess data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          python LongTermTravelPlanner/src/preprocess.py
