on:
  push:
    branches:
      - main
      - data/*
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r LongTermTravelPlanner/requirements.txt

      - name: Preprocess data
        run: |
          python LongTermTravelPlanner/src/preprocess.py
