# model_deploy.yml - 배포 전용 워크플로우
on:
  push:
    branches:  
      - deploy/data

jobs:
  preprocess_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 현재 브랜치 확인
      - name: Check branch
        run: |
          echo "Running on branch: ${GITHUB_REF#refs/heads/}"
          if [[ "${GITHUB_REF#refs/heads/}" != "main" && "${GITHUB_REF#refs/heads/}" != "feature/cicd" ]]; then
            echo "This workflow can only be run on the 'main' or 'feature/cicd' branches."
            exit 1
          fi

      # 3. Python 설치
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # 4. 필요한 패키지 설치
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r LongTermTravelPlanner/requirements.txt
          pip install boto3

      # 5. 전처리 과정 실행 (preprocess.py)
      - name: Preprocess data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          python LongTermTravelPlanner/src/preprocess.py
      - name: Verify processed train data file exists
        run: |
          ls -al LongTermTravelPlanner/data/processed/processed_train_data.csv

      # 6. S3로 전처리된 파일 업로드
      - name: Upload processed data to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PUBLIC_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 cp LongTermTravelPlanner/data/processed/processed_train_data.csv s3://$S3_BUCKET_NAME/LongTermDataFrame/data/processed/processed_train_data.csv
          aws s3 cp LongTermTravelPlanner/data/processed/processed_test_data.csv s3://$S3_BUCKET_NAME/LongTermDataFrame/data/processed/processed_test_data.csv
